apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.nuxeo.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.nuxeo.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.nuxeo.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.nuxeo.podAnnotations }}
      annotations:
{{ toYaml .Values.nuxeo.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.nuxeo.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.nuxeo.probePath }}
            port: {{ .Values.nuxeo.service.internalPort }}
          initialDelaySeconds: {{ .Values.nuxeo.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.nuxeo.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.nuxeo.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.nuxeo.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.nuxeo.probePath }}
            port: {{ .Values.nuxeo.service.internalPort }}
          periodSeconds: {{ .Values.nuxeo.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.nuxeo.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.nuxeo.readinessProbe.timeoutSeconds }}
        volumeMounts:
          - name: nuxeoconf
            mountPath: /docker-entrypoint-initnuxeo.d/  
      volumes:
      - name: nuxeoconf
        configMap:
          name: {{ template "fullname" . }}-conf 
        resources:
{{ toYaml .Values.nuxeo.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.nuxeo.terminationGracePeriodSeconds }}
