apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicemonitors.monitoring.coreos.com
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  group: monitoring.coreos.com
  version: v1
  names:
    kind: ServiceMonitor
    plural: servicemonitors
